INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (1, 1, 'Дж. К. Роулинг', 1, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (2, 1, 'Дж. Р. Р. Толкин', 1, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (3, 1, 'Дмитрий Емец', 1, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (4, 1, 'Г. Х. Андерсен', 1, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (5, 1, 'Есть', 2, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (6, 1, 'Читать', 2, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (7, 1, 'Думать', 2, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (8, 1, 'Говорить', 2, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (9, 1, 'Продать крестьян по подложным документам', 3, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (10, 1, 'Выгодно жениться', 3, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (11, 1, 'Купить дворянство', 3, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (12, 1, 'Получить большое поместье', 3, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (13, 1, '30 лет и 3 года', 4, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (14, 1, '30 лет', 4, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (15, 1, '30 лет и 2 года', 4, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (16, 1, '30 лет и 4 года', 4, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (17, 1, 'А.П.Чехов', 5, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (18, 1, 'М. Горький', 5, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (19, 1, 'Л. Н. Толстой', 5, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (20, 1, 'И. С. Тургенев', 5, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (21, 1, 'Михаил Васильевич Ломоносов ', 6, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (22, 1, 'Дмитрий Иванович Менделеев', 6, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (23, 1, 'Константин Эдуардович Циолковский', 6, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (24, 1, 'Софья Васильевна Ковалевская', 6, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (25, 1, '1865 ', 7, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (26, 1, '1864', 7, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (27, 1, '1866', 7, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (28, 1, '1867', 7, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (29, 1, '1189', 8, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (30, 1, '1190', 8, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (31, 1, '1188', 8, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (32, 1, '1187', 8, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (33, 1, '18', 9, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (34, 1, '19', 9, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (35, 1, '17', 9, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (36, 1, '16', 9, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (37, 1, '11', 10, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (38, 1, '10', 10, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (39, 1, '9', 10, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (40, 1, '12', 10, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (41, 1, '1922', 11, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (42, 1, '1921', 11, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (43, 1, '1920', 11, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (44, 1, '1923', 11, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (45, 1, '7', 12, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (46, 1, '6', 12, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (47, 1, '8', 12, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (48, 1, '5', 12, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (49, 1, '1', 13, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (50, 1, '5', 13, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (51, 1, '0', 13, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (52, 1, 'Бесконечность', 13, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (53, 1, 'Конденсатор', 14, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (54, 1, 'Транзистор', 14, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (55, 1, 'Реле', 14, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (56, 1, 'Резистор', 14, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (57, 1, 'Ом', 15, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (58, 1, 'Вольт', 15, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (59, 1, 'Ампер', 15, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (60, 1, 'Ньютон', 15, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (61, 1, 'Юпитера', 16, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (62, 1, 'Сатурна', 16, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (63, 1, 'Марса', 16, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (64, 1, 'Это не спутники', 16, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (65, 1, 'Икосаэдр', 17, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (66, 1, 'Плосконосый додекаэдр', 17, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (67, 1, 'Политоп', 17, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (68, 1, 'Пятиугольный гексаконтаэдр', 17, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (69, 1, 'черные дыры', 18, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (70, 1, 'астероиды', 18, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (71, 1, 'спутники', 18, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (72, 1, 'планеты', 18, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (73, 1, 'Пинакотека', 19, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (74, 1, 'Винотека', 19, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (75, 1, 'Дискотека', 19, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (76, 1, 'Библиотека', 19, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (77, 1, 'Пленэр', 20, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (78, 1, 'Карнация', 20, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (79, 1, 'Натюрморт', 20, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (80, 1, 'Граттаж', 20, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (85, 1, 'Импрессионизм', 21, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (86, 1, 'Кубизм', 21, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (87, 1, 'Экспрессионизм', 21, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (88, 1, 'Модернизм', 21, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (89, 1, 'Гюстав Эйфель', 22, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (90, 1, 'Ренцо Пиано', 22, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (91, 1, 'Антонио Гауди', 22, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (92, 1, 'Заха Хадид', 22, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (93, 1, 'каменные статуи на острове Пасхи', 23, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (94, 1, 'каменные столбы древних зданий на Гуаме', 23, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (95, 1, 'археологический памятник на территории Северной Македонии', 23, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (96, 1, 'каменное мегалитическое сооружение в графстве Уилтшир (Англия)', 23, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (97, 1, 'Леонардо ди сер Пьеро да Винчи', 24, 1);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (98, 1, 'Леонардо ди сер Анкиано да Винчи', 24, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (99, 1, 'Леонардо ди сер Амбуаза да Винчи', 24, 0);
INSERT INTO quiz.answers (id, is_active, text, question_id, is_true) VALUES (100, 1, 'Леонардо ди сер Америго да Винчи', 24, 0);