INSERT INTO quiz.questions (id, text, theme_id) VALUES (1, 'Кто автор серии книг о Гарри Поттере? ', 1);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (2, 'Что большинство людей не умеют делать, по мнению профессора Преображенского в повести Михаила Булгакова «Собачье сердце»?', 1);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (3, 'В поэме Гоголя «Мертвые души» Чичиков скупал мертвые души с целью...', 1);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (4, 'Сколько лет пролежал на печи известный богатырь Илья Муромец?', 1);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (5, 'Кому принадлежит выражение: «Краткость – сестра таланта»?', 1);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (6, 'Какой русский ученый сыграл главную роль в создании  первого в России университета?', 2);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (7, 'В каком году отменили рабство в США?', 2);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (8, 'В каком году начал править Ричард Львиное Сердце?', 2);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (9, 'Сколько раз Франция пересматривала свою конституцию?', 2);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (10, 'В каком веке был предпринят Первый крестовый поход?', 2);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (11, 'Когда завершился раздел Османской империи?', 2);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (12, 'В каком возрасте, согласно Плутарху, детей в Спарте распределяли по отрядам?', 2);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (13, 'Чему равно 5 в степени 0?', 3);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (14, 'Как называется прибор, накапливающий электрические заряды?', 3);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (15, 'В каких единицах измеряется напряжение?', 3);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (16, 'Ио, Европа, Ганимед - спутники...', 3);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (17, 'Геометрическая фигура близкая к шару, применяемая в создании современных футбольных мячей?', 3);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (18, 'TCI, IC 1101, S5 0014+81 - это...', 3);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (19, 'Как называется хранилище картин?', 4);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (20, 'Живопись на открытом воздухе — это...', 4);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (21, 'К какому направлению живописи относится картина Эдгара Дега «Голубые танцовщицы»?', 4);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (22, 'Кто стал архитектором знаменитой Статуи Свободы?', 4);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (23, 'Моаи — это...', 4);
INSERT INTO quiz.questions (id, text, theme_id) VALUES (24, null, 4);